LangString addOrReinstall ${LANG_PORTUGUESEBR} "Reparar instalação"
LangString alreadyInstalled ${LANG_PORTUGUESEBR} "ProjectFlow instalado"
LangString alreadyInstalledLong ${LANG_PORTUGUESEBR} "Esta mesma versão do ${PRODUCTNAME} já está instalada. Escolha Reparar instalação para restaurar os arquivos do aplicativo sem remover seus dados."
LangString appRunning ${LANG_PORTUGUESEBR} "{{product_name}} está aberto. Feche o aplicativo e tente novamente."
LangString appRunningOkKill ${LANG_PORTUGUESEBR} "{{product_name}} está aberto.$\nClique em OK para fechá-lo e continuar."
LangString chooseMaintenanceOption ${LANG_PORTUGUESEBR} "Escolha entre reparar ou desinstalar."
LangString choowHowToInstall ${LANG_PORTUGUESEBR} "Escolha como deseja continuar com o ${PRODUCTNAME}."
LangString createDesktop ${LANG_PORTUGUESEBR} "Criar atalho na área de trabalho"
LangString dontUninstall ${LANG_PORTUGUESEBR} "Atualizar sem desinstalar (recomendado)"
LangString dontUninstallDowngrade ${LANG_PORTUGUESEBR} "Manter a instalação atual (o downgrade está bloqueado)"
LangString failedToKillApp ${LANG_PORTUGUESEBR} "Não foi possível fechar {{product_name}}. Feche o aplicativo manualmente e tente novamente."
LangString installingWebview2 ${LANG_PORTUGUESEBR} "Instalando WebView2..."
LangString newerVersionInstalled ${LANG_PORTUGUESEBR} "Uma versão mais recente do ${PRODUCTNAME} já está instalada. O downgrade foi bloqueado para proteger seus dados."
LangString older ${LANG_PORTUGUESEBR} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_PORTUGUESEBR} "Uma versão $R4 do ${PRODUCTNAME} está instalada. Para atualizar preservando seus projetos e configurações, escolha Atualizar sem desinstalar (recomendado)."
LangString silentDowngrades ${LANG_PORTUGUESEBR} "O downgrade está bloqueado neste instalador. Use a interface gráfica para revisar a instalação.$\n"
LangString unableToUninstall ${LANG_PORTUGUESEBR} "Não foi possível concluir a instalação."
LangString uninstallApp ${LANG_PORTUGUESEBR} "Desinstalar ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_PORTUGUESEBR} "Desinstalar antes de instalar (não recomendado para atualização)"
LangString unknown ${LANG_PORTUGUESEBR} "desconhecida"
LangString webview2AbortError ${LANG_PORTUGUESEBR} "Não foi possível instalar o WebView2. O ProjectFlow precisa dele para funcionar. Reinicie o instalador."
LangString webview2DownloadError ${LANG_PORTUGUESEBR} "Erro ao baixar o WebView2: $0"
LangString webview2DownloadSuccess ${LANG_PORTUGUESEBR} "WebView2 baixado com sucesso"
LangString webview2Downloading ${LANG_PORTUGUESEBR} "Baixando WebView2..."
LangString webview2InstallError ${LANG_PORTUGUESEBR} "A instalação do WebView2 falhou com o código $1"
LangString webview2InstallSuccess ${LANG_PORTUGUESEBR} "WebView2 instalado com sucesso"
LangString deleteAppData ${LANG_PORTUGUESEBR} "Remover também projetos, configurações e dados locais"
